version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "qwerty123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes: 
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  linux:
     build:
        dockerfile: Dockerfile
  
volumes:
  data: