version: "3.9"
services:
  postgres:
    build: 
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes: 
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  linux:
    build:
        dockerfile: Dockerfile.ubuntu
    container_name: db-ubuntu
  
volumes:
  data: